spring:
  application:
    name: ensiibackend

  datasource:
    url: jdbc:postgresql://localhost:5432/ensii_dev
    username: ensii
    password: ensii

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  server:
    port: 8080

  management:
    endpoints.web.exposure.include: health,info
    endpoint.health.probes.enabled: true

  springdoc:
    swagger-ui:
      path: /swagger-ui

    api-docs:
      path: v3/api-docs